# Generated by Django 2.2.1 on 2020-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='media')),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
