# Generated by Django 2.2.1 on 2020-04-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20200410_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
