# Generated by Django 2.2.1 on 2020-04-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate', '0004_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000000)),
                ('genre', models.CharField(max_length=100000000000)),
                ('actors', models.CharField(max_length=10000000000)),
                ('director', models.CharField(max_length=100000000)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
