# Generated by Django 2.2.1 on 2020-04-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_auto_20200411_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
