# Generated by Django 2.2.1 on 2020-04-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20200411_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
