# Generated by Django 2.2.1 on 2020-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1000000000000000000, default=0, max_digits=1000000000000000000),
        ),
    ]
