# Generated by Django 2.2.1 on 2020-04-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_auto_20200413_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='score',
        ),
    ]
