# Generated by Django 2.2.1 on 2020-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0011_auto_20200413_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=10000000, default=0, max_digits=10000000),
        ),
    ]
