# Generated by Django 2.2.1 on 2020-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_auto_20200413_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1000, default=0, max_digits=10000),
        ),
    ]
