# Generated by Django 2.2.1 on 2020-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_auto_20200413_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
