# Generated by Django 2.2.1 on 2020-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_auto_20200413_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
